//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blood_Bank.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BloodBankEntities : DbContext
    {
        public BloodBankEntities()
            : base("name=BloodBankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blood_group> Blood_group { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Donor> Donors { get; set; }
        public virtual DbSet<Institute_Blood_Bank_stock> Institute_Blood_Bank_stock { get; set; }
        public virtual DbSet<patient> patients { get; set; }
        public virtual DbSet<rel_institute_city> rel_institute_city { get; set; }
        public virtual DbSet<tbl_Role> tbl_Role { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
        public virtual DbSet<BloodRequest> BloodRequests { get; set; }
    }
}
