//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blood_Bank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        public int patient_id { get; set; }
        public string patient_name { get; set; }
        public Nullable<int> patient_mbl { get; set; }
        public Nullable<System.DateTime> patient_birth_day { get; set; }
        public string patient_address { get; set; }
        public Nullable<int> blood_group_id { get; set; }
        public string sex { get; set; }
        public string photo { get; set; }
    
        public virtual Blood_group Blood_group { get; set; }
    }
}
